dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - docker
before_install:
  - docker pull jrabbit/taskd
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox-travis coverage
cache:
  directories:
    - $HOME/.cache/pypoetry/cache
script:  tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
